[project]
name = "language-from-zero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=6.5.1",
    "numpy>=2.4.2",
    "torch<2.3",
]
